server:
  port: 8085

spring:
  application:
    name: user-profile-service

astra:
  secure-connect-bundle: secure-connect-bundle.zip
  username: <client-id>
  password: <client-secret>
  keyspace: <keyspace>
